[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Allow these public API keys to be scanned without failing the build
  # These are client-side API keys for free public APIs (HUD & Census)
  SECRETS_SCAN_OMIT_KEYS = "VITE_CENSUS_API_KEY,VITE_HUD_API_KEY"

# Environment variables should be set in Netlify UI: Site Settings > Environment Variables
[build.processing]
  skip_processing = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

