import { FileDown } from 'lucide-react';
import { AnalysisResult } from '../types';
import { formatCurrency, formatPercentage, formatNumber } from '../utils/apiHelpers';
import jsPDF from 'jspdf';

interface PDFExportProps {
  result: AnalysisResult;
}

export function PDFExport({ result }: PDFExportProps) {
  const generatePDF = () => {
    const doc = new jsPDF();
    let yPos = 20;

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Section 8 Investment Analysis Report', 20, yPos);
    yPos += 10;

    // ZIP Code
    doc.setFontSize(16);
    doc.text(`ZIP Code: ${result.zipCode}`, 20, yPos);
    yPos += 15;

    // Investment Score
    if (result.investmentMetrics) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Investment Rating', 20, yPos);
      yPos += 8;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(`Score: ${result.investmentMetrics.score}/100 (Grade ${result.investmentMetrics.grade})`, 25, yPos);
      yPos += 6;
      doc.text(`Recommendation: ${result.investmentMetrics.recommendation}`, 25, yPos);
      yPos += 12;
    }

    // Fair Market Rent
    if (result.fmrData) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Fair Market Rent (FMR)', 20, yPos);
      yPos += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text(`Studio: ${formatCurrency(result.fmrData.data.fmr_0 || 0)}/mo`, 25, yPos);
      yPos += 6;
      doc.text(`1 Bedroom: ${formatCurrency(result.fmrData.data.fmr_1 || 0)}/mo`, 25, yPos);
      yPos += 6;
      doc.text(`2 Bedrooms: ${formatCurrency(result.fmrData.data.fmr_2 || 0)}/mo`, 25, yPos);
      yPos += 6;
      doc.text(`3 Bedrooms: ${formatCurrency(result.fmrData.data.fmr_3 || 0)}/mo`, 25, yPos);
      yPos += 6;
      doc.text(`4 Bedrooms: ${formatCurrency(result.fmrData.data.fmr_4 || 0)}/mo`, 25, yPos);
      yPos += 12;
    }

    // Investment Metrics
    if (result.investmentMetrics) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Key Investment Metrics', 20, yPos);
      yPos += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text(`Estimated Property Price: ${formatCurrency(result.investmentMetrics.estimatedPriceRange.median)}`, 25, yPos);
      yPos += 6;
      doc.text(`Required Rent (2% Rule): ${formatCurrency(result.investmentMetrics.requiredRentFor2Percent)}/mo`, 25, yPos);
      yPos += 6;
      doc.text(`Rent-to-Price Ratio: ${formatPercentage(result.investmentMetrics.rentToPriceRatio)}`, 25, yPos);
      yPos += 12;
    }

    // Crime Statistics
    if (result.crimeData) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Crime Statistics', 20, yPos);
      yPos += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text(`Violent Crime Rate: ${formatNumber(result.crimeData.violent_crime_rate)} per 100k`, 25, yPos);
      yPos += 6;
      doc.text(`Property Crime Rate: ${formatNumber(result.crimeData.property_crime_rate)} per 100k`, 25, yPos);
      yPos += 6;
      doc.text(`Total Incidents: ${formatNumber(result.crimeData.total_incidents)}`, 25, yPos);
      yPos += 12;
    }

    // Market Context
    if (result.marketContext) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Market Context', 20, yPos);
      yPos += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text(`County: ${result.marketContext.county}`, 25, yPos);
      yPos += 6;
      doc.text(`State: ${result.marketContext.state}`, 25, yPos);
      yPos += 6;
      if (result.marketContext.metroArea) {
        doc.text(`Metro Area: ${result.marketContext.metroArea}`, 25, yPos);
        yPos += 6;
      }
    }

    // Footer
    yPos = 280;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Section 8 Investment Analyzer', 20, yPos);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, yPos + 5);

    // Save the PDF
    doc.save(`section8-analysis-${result.zipCode}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="flex items-center gap-2 px-4 py-2 bg-primary text-white font-semibold rounded-lg hover:bg-blue-700 transition-all"
    >
      <FileDown className="w-5 h-5" />
      Export PDF Report
    </button>
  );
}

